### ISSUE TITLE
IndexOutOfRangeException when parsing any expression

### ISSUE THREAD

**Issue by mauricio-morales** [b3b00/csly#225]
As I was trying to migrate my Lexer from Regex to Generic, I ran (once again) into this `IndexOutOfRangeException`. 
I've actually seen it a few times in the past 2 days, and it typically goes away when I randomly move parser rules or lexer tokens up or down in the file. 

I've managed to reproduce it here for you to review when you get a chance :).

https://github.com/mauricio-morales/csly/tree/issue/224-index-out-of-range-exception

```
ParserTests.Issue224_IndexOutOfRangeException.IndexOutOfRangeTests.Should_Not_IndexOutOfRange

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at sly.parser.llparser.RecursiveDescentSyntaxParser`2.<>c__DisplayClass19_0.<ParseNonTerminal>b__1(Rule`1 r) in /csly/sly/parser/parser/llparser/RecursiveDescentSyntaxParser.cs:line 380
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at sly.parser.llparser.RecursiveDescentSyntaxParser`2.ParseNonTerminal(IList`1 tokens, NonTerminalClause`1 nonTermClause, Int32 currentPosition) in /csly/sly/parser/parser/llparser/RecursiveDescentSyntaxParser.cs:line 379
   at sly.parser.llparser.EBNFRecursiveDescentSyntaxParser`2.Parse(IList`1 tokens, Rule`1 rule, Int32 position, String nonTerminalName) in /csly/sly/parser/parser/llparser/EBNFRecursiveDescentSyntaxParser.cs:line 262
   at sly.parser.llparser.RecursiveDescentSyntaxParser`2.ParseNonTerminal(IList`1 tokens, NonTerminalClause`1 nonTermClause, Int32 currentPosition) in /csly/sly/parser/parser/llparser/RecursiveDescentSyntaxParser.cs:line 395
   at sly.parser.llparser.EBNFRecursiveDescentSyntaxParser`2.Parse(IList`1 tokens, Rule`1 rule, Int32 position, String nonTerminalName) in /csly/sly/parser/parser/llparser/EBNFRecursiveDescentSyntaxParser.cs:line 262
   at sly.parser.llparser.RecursiveDescentSyntaxParser`2.Parse(IList`1 tokens, String startingNonTerminal) in /csly/sly/parser/parser/llparser/RecursiveDescentSyntaxParser.cs:line 182
   at sly.parser.Parser`2.ParseWithContext(IList`1 tokens, Object parsingContext, String startingNonTerminal) in /csly/sly/parser/parser/Parser.cs:line 99
   at sly.parser.Parser`2.ParseWithContext(String source, Object context, String startingNonTerminal) in /csly/sly/parser/parser/Parser.cs:line 85
   at sly.parser.Parser`2.Parse(String source, String startingNonTerminal) in /csly/sly/parser/parser/Parser.cs:line 54
   at ParserTests.Issue224_IndexOutOfRangeException.IndexOutOfRangeTests.Parse(String query) in /csly/ParserTests/Issue224_IndexOutOfRangeException/IndexOutOfRangeTests.cs:line 32
   at ParserTests.Issue224_IndexOutOfRangeException.IndexOutOfRangeTests.Should_Not_IndexOutOfRange() in /csly/ParserTests/Issue224_IndexOutOfRangeException/IndexOutOfRangeTests.cs:line 13
```

Chances are there's something wrong with my code, but I can't figure out what it is and the error doesn't really give me any hint (not any obvious hint anyway).

**Comment by b3b00** [comment]
Debugging the issue i've just found that the IOR exception is raised when parsing your production rule

```c#
[Production("date_expression: INT DASH[d] INT DASH[d] INT T[d] INT COLON[d] INT COLON[d] INT Z[d] ( [PLUS|DASH] INT [SECOND|SECONDS|MINUTE|MINUTES|HOUR|HOURS|DAY|DAYS|WEEK|WEEKS|MONTH|MONTHS|YEAR|YEARS] )? ( SLASH[d] [HOUR|DAY|MONTH|YEAR] )?")]
```

This means that the issue is in CSLY : it should and must not crashed bu report an sensible error message. Still looking at what could be the root cause.

**Comment by b3b00** [comment]
Indeed there's something wrong with your grammar but I cannot not spot it though I suspect the expression hierarchy
expression -> tertiary_expression -> secondary_expression 

bUt there are 2 things here : 

1. an error in the grammar
2. a lack of error reporting in CSLY

I made your test pass simplifying your grammar, simply removing the following rule : 

```c#
[Production("tertiary_expression: secondary_expression OR tertiary_expression")]
```

that what makes me think there is an issue with the grammar

**Comment by b3b00** [comment]
I've found a partial fix that makes e back to your previous issue #223.
Your grammar should be fine after I'll fix it. 
I will come to it later.
