### ISSUE TITLE
error : unexpected end of stream. Expecting <<EOS>>. 

### ISSUE THREAD

**Issue by lijiajunply** [b3b00/csly#338]

**Comment by lijiajunply** [comment]
the error parser :
statement: CLASS[d] IDENTIFIER INDENT[d] set* UINDENT[d]
set: IDENTIFIER SET[d] OldParser_expressions
the test context:
class a
   a = 1

**Comment by lijiajunply** [comment]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ManySyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.Parser`2.ParseWithContext(IList`1 tokens, Object parsingContext, String startingNonTerminal)
   at sly.parser.Parser`2.Parse(String source, String startingNonTerminal)

**Comment by lijiajunply** [comment]
now error:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ManySyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(SyntaxNode`1 node, Object context)
   at sly.parser.generator.visitor.EBNFSyntaxTreeVisitor`2.Visit(ISyntaxNode`1 n, Object context)
   at sly.parser.Parser`2.ParseWithContext(IList`1 tokens, Object parsingContext, String startingNonTerminal)
   at sly.parser.Parser`2.Parse(String source, String startingNonTerminal)

text context:
class a
   a = 1

**Comment by lijiajunply** [comment]
the error parser :
statement: CLASS[d] IDENTIFIER INDENT[d] set* UINDENT[d]
set: IDENTIFIER SET[d] OldParser_expressions
the test context:
class a

**Comment by lijiajunply** [comment]
i find it
